apiVersion: v1
kind: Namespace
metadata:
  name: cybericebox
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: cybericebox
data:
  DOMAIN: cybericebox.com # domain of the platform
  RECAPTCHA_KEY: ...
  RECAPTCHA_SECRET: ...
  JWT_TOKEN_SIGNATURE: "random" # for signing JWT tokens
  GOOGLE_CLIENT_ID: ...
  GOOGLE_SECRET: ...
  EMAIL_HOST: smtp.gmail.com
  EMAIL_USERNAME: noreply.cybericebox@gmail.com
  EMAIL_PASSWORD: ...
  EMAIL_SENDER_NAME: "Cyber ICE Box Platform"
  EMAIL_SENDER_EMAIL: noreply@cybericebox.com
  EMAIL_REPLY_TO_NAME: "Support Cyber ICE Box Platform"
  EMAIL_REPLY_TO_EMAIL: support@cybericebox.com
  POSTGRES_HOSTNAME: "hostname"
  POSTGRES_USER: "username"
  POSTGRES_PASSWORD: "password"
  POSTGRES_DB: "database"
  POSTGRES_SSL_MODE: "disable"
  WG_GRPC_AUTH_KEY: "randomkey"
  WG_GRPC_SIGN_KEY: "randomkey"
  VPN_ENDPOINT: vpn.cybericebox.com:51820
  AGENT_GRPC_AUTH_KEY: "randomkey"
  AGENT_GRPC_SIGN_KEY: "randomkey"
  LABS_CIDR: 128.0.0.0/8
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: subnet-address
  namespace: metallb-system
spec:
  addresses:
  - 192.168.10.0/32 # address of internal subnet
