apiVersion: v1
kind: Namespace
metadata:
  name: cybericebox
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
  namespace: cybericebox
data:
  DOMAIN: cybericebox.com # domain of the paltform
  RECAPTCHA_KEY: ...
  RECAPTCHA_SECRET: ...
  JWT_TOKEN_SIGNATURE: "random" # for signing JWT tokens
  GOOGLE_CLIENT_ID: ...
  GOOGLE_SECRET: ...
  EMAIL_HOST: smtp.gmail.com
  EMAIL_USERNAME: noreply.cybericebox@gmail.com
  EMAIL_PASSWORD: ...
  EMAIL_SENDER_NAME: "Cyber ICE Box Platform"
  EMAIL_SENDER_EMAIL: noreply@cybericebox.com
  EMAIL_REPLY_TO_NAME: "Support Cyber ICE Box Platform"
  EMAIL_REPLY_TO_EMAIL: support@cybericebox.com
  POSTGRES_HOSTNAME: hostname
  POSTGRES_USER: username
  POSTGRES_PASSWORD: password
  POSTGRES_DB: database
  POSTGRES_SSL_MODE: require
  WG_GRPC_AUTH: "random"
  WG_GRPC_SIGN: "random"
  VPN_ENDPOINT: vpn.cybericebox.com:31820
  AGENT_GRPC_AUTH: "random"
  AGENT_GRPC_SIGN: "random"
  LAB_CIDR: 128.0.0.0/8
